# experiment name
work_dir: ./work_dir_poly
task_name: poly_test

# dataset
data_type: polyp
image_root: /media/gallade/RAID/hu/dataset/Kvasir-SEG/images
gt_root: /media/gallade/RAID/hu/dataset/Kvasir-SEG/masks_new
separate_info: /media/gallade/RAID/hu/dataset/Kvasir-SEG/fold_info/kvasir_fold_0.csv

# prompt flag: bbox, simple, mix
prompt_flag: bbox

#model 
model_type: vit_b
checkpoint: /media/gallade/RAID/hu/model/sam_vit_b_01ec64.pth
device: cuda:0

#train 
num_epochs: 31
eval_epoch: 1
batch_size: 2
warm_iter: 0
lr: 0.0001
weight_decay: 0
seed: 0

#adapter
adapter: True
finetune_all: False
adapter_type: spa # spa
attn_type: deformable # global deformable

#deformable
deform_num_heads: 16
n_level_list: [16,] # feature level used in SPM
# interaction_indexes: [[0, 7], [8, 15], [16, 23], [24, 31]] # The depth of VIT-h is 32
# interaction_indexes: [[0, 5], [6, 11], [12, 17], [18, 23]] # The depth of VIT-l is 24
interaction_indexes: [[0, 2], [3, 5], [6, 8], [9, 11]] # The depth of VIT-b is 12
n_points: 4
init_values: 0.00001
with_cffn: True
drop_path: 0.3
cffn_ratio: 0.25
deform_ratio: 0.5
with_cp: True # set with_cp=True to save memory

